/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Es la clase encargada de realizar el cambio de moneda
 * con el tipo de cambio
 * @author Milena
 */
public class CambioMoneda extends javax.swing.JFrame {
  public Fondo imagen = new Fondo();
  static String cuenta;
  static String tarjeta;
     CambiosEnSaldo camb = new CambiosEnSaldo();
     funcionalidad fun = new funcionalidad();
    public CambioMoneda(String cuenta,String tarjeta) {
        this.cuenta=cuenta;
        this.tarjeta=tarjeta;
       this.setContentPane(imagen);
        initComponents();
        setResizable(false);
                /*---------------------------------------------- parte de los botones1----------------------------------------------*/
        dolar1.setIcon(setIcono("/imagenes/dolar.png",dolar1));
        dolar1.setPressedIcon(setIconoPrecionado("/imagenes/dolar.png",dolar1,30,30));
           /*---------------------------------------------- parte de los botones2----------------------------------------------*/
        euro1.setIcon(setIcono("/imagenes/euro.png",euro1));
        euro1.setPressedIcon(setIconoPrecionado("/imagenes/euro.png",euro1,30,30));
            /*---------------------------------------------- parte de los botones3----------------------------------------------*/
        bol1.setIcon(setIcono("/imagenes/bol.png",bol1));
        bol1.setPressedIcon(setIconoPrecionado("/imagenes/bol.png",bol1,30,30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        euro1 = new javax.swing.JButton();
        bol1 = new javax.swing.JButton();
        dolar1 = new javax.swing.JButton();
        imagen2 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        euro1.setBorderPainted(false);
        euro1.setContentAreaFilled(false);
        euro1.setFocusPainted(false);
        euro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euro1ActionPerformed(evt);
            }
        });

        bol1.setBorderPainted(false);
        bol1.setContentAreaFilled(false);
        bol1.setFocusPainted(false);
        bol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bol1ActionPerformed(evt);
            }
        });

        dolar1.setBorderPainted(false);
        dolar1.setContentAreaFilled(false);
        dolar1.setFocusPainted(false);
        dolar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolar1ActionPerformed(evt);
            }
        });

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        texto2.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 51, 102));
        texto2.setText("Elija el cambio de moneda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(euro1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dolar1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bol1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(imagen2)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(texto2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(texto2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dolar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(euro1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(bol1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Maneja la conversión de la cuenta bancaria a euros cuando se acciona 
     * el evento del botón.
     * Verifica el saldo en el archivo de cuenta y realiza las conversiones necesarias
     * desde bolivianos o dólares a euros, si es necesario.
     * @param evt 
     */
    private void euro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euro1ActionPerformed
        //-------------------------------------------------------------------------------------------
        boolean euros = camb.lineaContieneEu("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          boolean bolivianos = camb.lineaContieneBs("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          boolean dolares = camb.lineaContieneDlr("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          double sald= fun.leerSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
            //-------------------------------------------------------------------------------------------
       if(euros==true){
           JOptionPane.showMessageDialog(null, "SU CUENTA YA SE ENCUENTRA EN EUROS!!");
             menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
       }
        if(bolivianos==true){
            double nuev = camb.bolivianosAEuros(sald);
            System.out.println(nuev);
            //-------------------------------------------------------------------------------------------
            camb.reemplazarEuPorBs("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",nuev);
            //-------------------------------------------------------------------------------------------
              JOptionPane.showMessageDialog(null, "OPERACION REALIZADA CON EXITO");
              historial his = new historial(cuenta,"SE CAMBIO DE BOLIVIANOS A EUROS");
              his.guardar();
   menu  v = new menu(tarjeta,cuenta);
   v.setVisible(true);
        dispose();
        }
        if(dolares==true){
            double nuev = camb.dolaresAEuros(sald);
            //-------------------------------------------------------------------------------------------
             camb.reemplazarEuPorDlr("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",nuev);
             //-------------------------------------------------------------------------------------------
                   JOptionPane.showMessageDialog(null, "OPERACION REALIZADA CON EXITO");
                  historial his = new historial(cuenta,"SE CAMBIO DE DOLARES A EUROS");
                  his.guardar();
                   menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_euro1ActionPerformed
    /**
     * Maneja la conversión de la cuenta bancaria a bolivianos cuando se acciona 
     * el evento del botón.
     * Verifica el saldo en el archivo de cuenta y realiza las conversiones necesarias
     * desde euros o dólares a bolivianos, si es necesario.
     * @param evt 
     */
    private void bol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bol1ActionPerformed
   //-------------------------------------------------------------------------------------------
        boolean euros = camb.lineaContieneEu("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          boolean boliviano = camb.lineaContieneBs("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          boolean dolares = camb.lineaContieneDlr("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          double sald= fun.leerSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
         //-------------------------------------------------------------------------------------------          
       if(boliviano==true){
           JOptionPane.showMessageDialog(null, "SU CUENTA YA SE ENCUENTRA EN BOLIVIANOS!!");
           menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
       }
        if(dolares==true){
            double nuev = camb.dolaresABolivianos(sald);
            //-------------------------------------------------------------------------------------------
            camb.reemplazarBsPorDlr("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",nuev);
            //-------------------------------------------------------------------------------------------
            JOptionPane.showMessageDialog(null, "OPERACION REALIZADA CON EXITO");
             historial his = new historial(cuenta,"SE CAMBIO DE DOLARES A BOLIVIANOS");
             his.guardar();
             menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
        }
        if(euros==true){
        double nuev = camb.eurosABolivianos(sald);
        //-------------------------------------------------------------------------------------------
                camb.reemplazarBsPorEu("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",nuev);
         //-------------------------------------------------------------------------------------------
                JOptionPane.showMessageDialog(null, "OPERACION REALIZADA CON EXITO");
         historial his = new historial(cuenta,"SE CAMBIO DE EUROS A BOLIVIANOS");
         his.guardar();
            menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
        }
       
      
        
    }//GEN-LAST:event_bol1ActionPerformed
    /**
     * Maneja la conversión de la cuenta bancaria a dólares cuando se acciona 
     * el evento del botón.
     * Verifica el saldo en el archivo de cuenta y realiza las conversiones necesarias
     * desde euros o bolivianos a dólares, si es necesario.
     * @param evt 
     */
    private void dolar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolar1ActionPerformed
        //-------------------------------------------------------------------------------------------  
        boolean euros = camb.lineaContieneEu("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          boolean bolivianos = camb.lineaContieneBs("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          boolean dolares = camb.lineaContieneDlr("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
          double sald= fun.leerSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");
         //-------------------------------------------------------------------------------------------
        if(dolares==true){
           JOptionPane.showMessageDialog(null, "SU CUENTA YA SE ENCUENTRA EN DOLARES!!");
           menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
       }
        if(bolivianos==true){
            double nuev = camb.bolivianosADolares(sald);
            //------------------------------------------------------------------------------------------- 
           camb.reemplazarDlrPorBs("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",nuev);
           //------------------------------------------------------------------------------------------- 
           JOptionPane.showMessageDialog(null, "OPERACION REALIZADA CON EXITO");
            historial his = new historial(cuenta,"SE CAMBIO DE BOLIVIANOS A DOLARES");
            his.guardar();
         menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
        }
        if(euros==true){
            double nuev = camb.eurosADolares(sald);
            //------------------------------------------------------------------------------------------- 
            camb.reemplazarDlrPorEu("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",nuev);
            //-------------------------------------------------------------------------------------------
            JOptionPane.showMessageDialog(null, "OPERACION REALIZADA CON EXITO");
            historial his = new historial(cuenta,"SE CAMBIO DE EUROS A DOLARES");
            his.guardar();
           menu  v = new menu(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
        }
        
    }//GEN-LAST:event_dolar1ActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioMoneda(cuenta,tarjeta).setVisible(true);
            }
        });
    }
    /**
     * Clase interna para establecer una imagen de fondo en un JPanel.
     */
       class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * Establece un ícono en un botón con una imagen escalada al tamaño del botón.
     * @param url la ruta de la imagen a usar como ícono
     * @param b el botón en el que se establecerá el ícono
     * @return el ícono escalado
     */
     public Icon setIcono(String url,JButton b){
         ImageIcon  icon= new ImageIcon(getClass().getResource(url)); 
         int ancho =b.getWidth();
         int alto =b.getHeight();
         ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT)); 
         return icono;
     }
     /**
      * Establece un ícono en un botón para el estado presionado, con una imagen escalada
      * al tamaño especificado.
      * @param url la ruta de la imagen a usar como ícono
      * @param b el botón en el que se establecerá el ícono
      * @param ancho la cantidad de píxeles para reducir el ancho del ícono
      * @param alto la cantidad de píxeles para reducir el alto del ícono
      * @return el ícono escalado para el estado presionado
      */
     public Icon setIconoPrecionado(String url,JButton b,int ancho,int alto){
       
         ImageIcon icon= new ImageIcon(getClass().getResource(url));
          int  width = b.getWidth()- ancho;
          int height = b.getHeight() - alto;
          ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width,height,Image.SCALE_DEFAULT));
          return icono;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bol1;
    private javax.swing.JButton dolar1;
    private javax.swing.JButton euro1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
