/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * La clase principal, de donde al ingresar se podrá
 * acceder al menú con las demás funciones
 * @author Milena
 */
public class inicio extends javax.swing.JFrame {
     String tarjetaText;
     String pinText;
     int pin;

/**
 * metodo para cambiar idiomas   
 */ 
 public void cambiarTextos() {
        if ("Русский".equals((String) idiomas.getSelectedItem())) {
            // Cambiar los textos de los componentes
            texto1.setText("ДОБРО ПОЖАЛОВАТЬ");
            texto2.setText("БАНАНИТА НАЦИОНАЛЬНЫЙ БАНК");
            texto3.setText("(Внимание 24 часа в сутки)");
            texto4.setText("Введите номер вашей карты:");
            texto5.setText("выберите язык: ");
            texto6.setText("банка");
            texto7.setText("введите свой PIN-код:");
            text7.setText("банановая");
            sig.setText("Nuevo texto en el botón");
        } else {
            if ("English".equals((String) idiomas.getSelectedItem())) {
            // Cambiar los textos de los componentes
            texto1.setText("WELCOME");
            texto2.setText("BANANITA NATIONAL BANK");
            texto3.setText("(Attention 24 hours a day)");
            texto4.setText("Enter your Card number:");
            texto5.setText("Select a language");
            texto6.setText("Bank");
            texto7.setText("Enter your pin: ");
            text7.setText("Banana");
            sig.setText("Nuevo texto en el botón");
           } else {
                    if ("Español".equals((String) idiomas.getSelectedItem())) {
                    // Cambiar los textos de los componentes
                     texto1.setText("BIENVENIDOS");
                     texto2.setText("BANCO NACIONAL BANANITA");
                     texto3.setText("(Atención las 24 hrs del día)");
                     texto4.setText("Ingrese su número de Tarjeta:");
                     texto5.setText("Selecciona un lenguaje");
                     texto6.setText("Banco");
                     texto7.setText("Ingrese su pin: ");
                     text7.setText("Bananita");
                     sig.setText("Nuevo texto en el botón");
                     }
                   }
        }
    }

 public Fondo imagen = new Fondo();
 /**
  * Crea una instancia de la clase inicio
  */
    public inicio() {
        this.setContentPane(imagen);
        initComponents();  
        
        setResizable(false);
                /*---------------------------------------------- parte de los botones----------------------------------------------*/
        sig.setIcon(setIcono("/imagenes/sig.png",sig));
        sig.setPressedIcon(setIconoPrecionado("/imagenes/sig.png",sig,30,30));
          
    }
    
    funcionalidad fun = new funcionalidad();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        sig = new javax.swing.JButton();
        imagen2 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        text7 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        idiomas = new javax.swing.JComboBox<>();
        texto4 = new javax.swing.JLabel();
        numCuenta = new javax.swing.JTextField();
        texto7 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto1.setBackground(new java.awt.Color(102, 0, 102));
        texto1.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        texto1.setForeground(new java.awt.Color(0, 102, 153));
        texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto1.setText("BIENVENIDOS ");

        texto2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 51, 102));
        texto2.setText("BANCO NACIONAL BANANITA");

        texto3.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        texto3.setForeground(new java.awt.Color(0, 51, 153));
        texto3.setText("(Atención las 24 horas del día)");

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        sig.setBorderPainted(false);
        sig.setContentAreaFilled(false);
        sig.setFocusPainted(false);
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        texto6.setBackground(new java.awt.Color(51, 51, 51));
        texto6.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        texto6.setForeground(new java.awt.Color(0, 51, 153));
        texto6.setText("Banco");

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        text7.setBackground(new java.awt.Color(255, 153, 0));
        text7.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        text7.setForeground(new java.awt.Color(0, 51, 153));
        text7.setText("Bananita");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text7, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        texto5.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        texto5.setForeground(new java.awt.Color(0, 51, 102));
        texto5.setText("Selecciona un idioma:");
        texto5.setToolTipText("");

        idiomas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        idiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "English", "Русский", " " }));
        idiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomasActionPerformed(evt);
            }
        });

        texto4.setBackground(new java.awt.Color(255, 255, 255));
        texto4.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        texto4.setForeground(new java.awt.Color(0, 51, 102));
        texto4.setText("Ingrese su número de Tarjeta:");
        texto4.setToolTipText("");

        numCuenta.setBackground(new java.awt.Color(255, 204, 51));
        numCuenta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        numCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));
        numCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCuentaActionPerformed(evt);
            }
        });

        texto7.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        texto7.setForeground(new java.awt.Color(0, 51, 102));
        texto7.setText("Ingrese su PIN:");
        texto7.setToolTipText("");

        contra.setBackground(new java.awt.Color(255, 204, 51));
        contra.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contra.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));
        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(texto2)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(texto5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texto7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numCuenta))))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sig, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagen1))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texto5)
                                    .addComponent(idiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texto4))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texto7)
                                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagen1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sig, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaActionPerformed
    /**
     * Al hacer click en el botón de siguiente, verifica si
     * la tarjeta y su pin existen
     * @param evt click en el botón
     */
    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
         tarjetaText = numCuenta.getText();
        int tarjeta = Integer.parseInt(tarjetaText);
        pinText =  contra.getText();
         pin = Integer.parseInt(pinText);
         
          if (verificarCredenciales()) {
       CuentasBotones v = new CuentasBotones( tarjetaText);
        String dato = numCuenta.getText();
         
        numCuenta.setText("");
        numCuenta.requestFocus();
        v.setVisible(true);
        dispose(); 
    } else {
        JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR PIN O TARJETA NO EXISTE");
    }
         
         

    }//GEN-LAST:event_sigActionPerformed

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void idiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomasActionPerformed
        cambiarTextos();
    }//GEN-LAST:event_idiomasActionPerformed
    

 
    /**
     * devuelve el  jcombobox de idiomas 
     * @return 
     */  
    public JComboBox<String> getIdiomasComboBox() {
        return idiomas;
    }
    /**
     * Verifica en los archivos si los datos ingresados coinciden 
     * @return true en caso de que los datos coinciden, false en caso contrario
     */
    private boolean verificarCredenciales() {
              //----------------------------------------------------------------------------------------------------------------
        boolean existe = fun.verificarExistencia("C:\\Users\\Milena\\taller de pogra\\tarjetas\\" + tarjetaText + ".txt");
        boolean existeCont = pin==(fun.leerPin("C:\\Users\\Milena\\taller de pogra\\tarjetas\\" + tarjetaText + ".txt"));
        //-----------------------------------------------------------------------------------------------------------------------------------

        System.out.println("Existe usuario: " + existe);
        System.out.println("Coincide contraseña: " + existeCont);

        return (existe && existeCont);
    }
    
    
    /**
     
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new inicio().setVisible(true);
            }
        });
    }
    /**
     * Clase interna para representar un panel con una imagen de fondo.
     */
   class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * Establece un ícono redimensionado en un botón.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @return el ícono redimensionado
     */
     public Icon setIcono(String url,JButton b){
         ImageIcon  icon= new ImageIcon(getClass().getResource(url)); 
         int ancho =b.getWidth();
         int alto =b.getHeight();
         ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT)); 
         return icono;
     }
    /**
     * Establece un ícono redimensionado en un botón cuando se presiona.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @param ancho el ancho del ícono redimensionado
     * @param alto el alto del ícono redimensionado
     * @return el ícono redimensionado
     */
     public Icon setIconoPrecionado(String url,JButton b,int ancho,int alto){
       
         ImageIcon icon= new ImageIcon(getClass().getResource(url));
          int  width = b.getWidth()- ancho;
          int height = b.getHeight() - alto;
          ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width,height,Image.SCALE_DEFAULT));
          return icono;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contra;
    private javax.swing.JComboBox<String> idiomas;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numCuenta;
    private javax.swing.JButton sig;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    // End of variables declaration//GEN-END:variables
}
