/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.awt.Graphics;
import java.awt.Image;



import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 * Clase donde se encuentran botones que dirigen a las distintas funcionalidades
 * @author Milena
 */
public class menu extends javax.swing.JFrame {
     private JComboBox<String> idiomasComboBox;
  static  String tarjeta;
  static String cuenta;
    public Fondo imagen = new Fondo();
    
    public menu(String tarjeta,String cuenta) {
           funcionalidad ddd = new funcionalidad();
           //----------------------------------------------//----------------------------------------------//----------------------------------------------//----------------------------------------------
        String nomn = ddd.obtenerNombre("C:\\Users\\Milena\\taller de pogra\\tarjetas\\" + tarjeta + ".txt"); 

        //----------------------------------------------//----------------------------------------------//----------------------------------------------
       this.setContentPane(imagen);
        initComponents();
        transp(nomn,cuenta);
        this.tarjeta=tarjeta;
       this.cuenta=cuenta;
    
        setResizable(false);

        // Crear un panel
        JPanel panel = new JPanel();
        panel.setLayout(null); // -------------------------- parte de los botones1----------------------------------------------*/
        saldo.setIcon(setIcono("/imagenes/constSaldo.png",saldo));
        saldo.setPressedIcon(setIconoPrecionado("/imagenes/constSaldo.png",saldo,30,30));
          /*---------------------------------------------- parte de los botones2----------------------------------------------*/
        retirar.setIcon(setIcono("/imagenes/retirar.png",retirar));
        retirar.setPressedIcon(setIconoPrecionado("/imagenes/retirar.png",retirar,30,30));
           /*---------------------------------------------- parte de los botones3----------------------------------------------*/
        depositar.setIcon(setIcono("/imagenes/depositar.png",depositar));
        depositar.setPressedIcon(setIconoPrecionado("/imagenes/depositar.png",depositar,30,30));
         /*---------------------------------------------- parte de los botones4----------------------------------------------*/
        transferir.setIcon(setIcono("/imagenes/transferir.png",transferir));
        transferir.setPressedIcon(setIconoPrecionado("/imagenes/transferir.png",transferir,30,30));
          /*---------------------------------------------- parte de los botones5----------------------------------------------*/
        contra.setIcon(setIcono("/imagenes/contra.png",contra));
        contra.setPressedIcon(setIconoPrecionado("/imagenes/contra.png",contra,30,30));
          /*---------------------------------------------- parte de los botones6----------------------------------------------*/
        atras.setIcon(setIcono("/imagenes/atras.png",atras));
        atras.setPressedIcon(setIconoPrecionado("/imagenes/atras.png",atras,30,30));
    /*---------------------------------------------- parte de los botones7----------------------------------------------*/
        cambio.setIcon(setIcono("/imagenes/moneda.png",cambio));
        cambio.setPressedIcon(setIconoPrecionado("/imagenes/moneda.png",cambio,30,30));

    }
   
    /**
     * Metodo odiomas
     */
  public void cambiarTextos() {
      String leng = (String) idiomasComboBox.getSelectedItem();

        if ("Русский".equals(leng)) {
            // Cambiar los textos de los componentes
            texto1.setText("Имя:");
            texto2.setText("Выберите тип транзакции, который вы хотите");
            
        
        } else {
            if ("English".equals(leng)) {
            // Cambiar los textos de los componentes
            texto1.setText("Name:");
            texto2.setText("Choose the type of Transaction you want");
            
         
           } else {
                    if ("Español".equals(leng)) {
                    // Cambiar los textos de los componentes
                     texto1.setText("Nombre");
                     texto2.setText("Elige el tipo de Transaccion Que quieras");
                  
                     }
                   }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idiomas = new javax.swing.JComboBox<>();
        retirar = new javax.swing.JButton();
        depositar = new javax.swing.JButton();
        contra = new javax.swing.JButton();
        transferir = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        BTNnombre = new javax.swing.JButton();
        cambio = new javax.swing.JButton();
        numCuentaLBL = new javax.swing.JLabel();

        idiomas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        idiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "English", "Русский", " " }));
        idiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        retirar.setBorderPainted(false);
        retirar.setContentAreaFilled(false);
        retirar.setFocusPainted(false);
        retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarActionPerformed(evt);
            }
        });

        depositar.setBorderPainted(false);
        depositar.setContentAreaFilled(false);
        depositar.setFocusPainted(false);
        depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarActionPerformed(evt);
            }
        });

        contra.setBorderPainted(false);
        contra.setContentAreaFilled(false);
        contra.setFocusPainted(false);
        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });

        transferir.setBorderPainted(false);
        transferir.setContentAreaFilled(false);
        transferir.setFocusPainted(false);
        transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirActionPerformed(evt);
            }
        });

        saldo.setBorderPainted(false);
        saldo.setContentAreaFilled(false);
        saldo.setFocusPainted(false);
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        texto2.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 51, 102));
        texto2.setText("Elige el tipo de Transaccion que quieras ");

        texto6.setBackground(new java.awt.Color(51, 51, 51));
        texto6.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        texto6.setText("BNB");

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setFocusPainted(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        texto1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        texto1.setForeground(new java.awt.Color(0, 102, 153));
        texto1.setText("Cuentas:");

        texto4.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        texto4.setForeground(new java.awt.Color(0, 102, 153));
        texto4.setText("Nombre:");

        BTNnombre.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        BTNnombre.setForeground(new java.awt.Color(0, 102, 153));
        BTNnombre.setText("jButton1");

        cambio.setBorderPainted(false);
        cambio.setContentAreaFilled(false);
        cambio.setFocusPainted(false);
        cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioActionPerformed(evt);
            }
        });

        numCuentaLBL.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        numCuentaLBL.setForeground(new java.awt.Color(0, 102, 153));
        numCuentaLBL.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numCuentaLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto2)
                            .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143))))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(depositar, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1014, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(texto6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCuentaLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addComponent(texto2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(depositar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Dirige a la ventana de retiros
     * @param evt Click en el botón
     */
    private void retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarActionPerformed

        retiros v = new retiros(cuenta,tarjeta);
             v.setVisible(true);
             dispose();
    }//GEN-LAST:event_retirarActionPerformed
    /**
     * Dirige a la ventana de depositos
     * @param evt Click en el botón
     */
    private void depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarActionPerformed
          
          OtroMontoI v = new OtroMontoI(cuenta,tarjeta);
           v.setVisible(true);
             dispose();
    }//GEN-LAST:event_depositarActionPerformed
    /**
     * Dirige a la ventana de transferencias
     * @param evt Click en el botón
     */
    private void transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirActionPerformed
              
        OtraCuenta v = new OtraCuenta(cuenta,tarjeta);
           v.setVisible(true);
             dispose();
    }//GEN-LAST:event_transferirActionPerformed
    /**
     * Dirige a la ventana de cambio de contraseña
     * @param evt Click en el botón 
     */
    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        contra  v = new contra(tarjeta,cuenta);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_contraActionPerformed
    /**
     * Dirige a la ventana de cuentas
     * @param evt Click en el botón
     */
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
             CuentasBotones  v = new CuentasBotones(tarjeta);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /** 
     * Dirige a la ventana de saldo
     * @param evt Click en el botón
     */
    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
         SaldoCuentas s= new SaldoCuentas(cuenta,tarjeta);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_saldoActionPerformed
    
    private void idiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomasActionPerformed
  
    }//GEN-LAST:event_idiomasActionPerformed
    /**
     * Dirige a la ventana de cambio de moneda
     * @param evt Click en el botón
     */
    private void cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioActionPerformed

        CambioMoneda  v = new CambioMoneda(cuenta,tarjeta);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_cambioActionPerformed
    /**
     * Coloca los datos dentro de la ventana para saber la cuenta y su propietario
     * @param nom nombre de la persona
     * @param cuenta cuenta actual
     */
    public void transp(String nom,String cuenta){
          
        BTNnombre.setText(nom);
              numCuentaLBL.setText(cuenta);
                BTNnombre.setContentAreaFilled(false);
                BTNnombre.setBorderPainted(false);
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new menu(tarjeta,cuenta).setVisible(true);
            }
        });
    }
    /**
     * Clase interna para representar un panel con una imagen de fondo.
     */
   class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
      class Azul extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_1.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * Establece un ícono redimensionado en un botón.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @return el ícono redimensionado
     */
     public Icon setIcono(String url,JButton b){
         ImageIcon  icon= new ImageIcon(getClass().getResource(url)); 
         int ancho =b.getWidth();
         int alto =b.getHeight();
         ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT)); 
         return icono;
     }
    /**
     * Establece un ícono redimensionado en un botón cuando se presiona.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @param ancho el ancho del ícono redimensionado
     * @param alto el alto del ícono redimensionado
     * @return el ícono redimensionado
     */
     public Icon setIconoPrecionado(String url,JButton b,int ancho,int alto){
       
         ImageIcon icon= new ImageIcon(getClass().getResource(url));
          int  width = b.getWidth()- ancho;
          int height = b.getHeight() - alto;
          ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width,height,Image.SCALE_DEFAULT));
          return icono;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNnombre;
    private javax.swing.JButton atras;
    private javax.swing.JButton cambio;
    private javax.swing.JButton contra;
    private javax.swing.JButton depositar;
    private javax.swing.JComboBox<String> idiomas;
    private javax.swing.JLabel numCuentaLBL;
    private javax.swing.JButton retirar;
    private javax.swing.JButton saldo;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto6;
    private javax.swing.JButton transferir;
    // End of variables declaration//GEN-END:variables
 
}
