/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import static cajero.CambioMoneda.cuenta;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Clase que representa una interfaz gráfica de usuario para manejar 
 * transacciones a otra cuenta bancaria.
 * @author Milena
 */
public class OtraCuenta extends javax.swing.JFrame {
     static String cuenta;
     static String tarjeta;
     static String cuentaADepositar;
      public Fondo imagen = new Fondo(); 
    /**
     * Crea una nueva instancia de OtraCuenta.
     * 
     * @param cuenta la cuenta desde la cual se realizará la transacción
     * @param tarjeta la tarjeta asociada a la cuenta
     */
      public OtraCuenta(String cuenta, String tarjeta) {
          this.cuenta=cuenta;
          this.tarjeta=tarjeta;
          this.setContentPane(imagen);
        initComponents();
        setResizable(false);
                /*---------------------------------------------- parte de los botones1----------------------------------------------*/
        confirmar.setIcon(setIcono("/imagenes/confirmar.png",confirmar));
        confirmar.setPressedIcon(setIconoPrecionado("/imagenes/confirmar.png",confirmar,30,30));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto6 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        numCuenta = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        imagen2 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto6.setBackground(new java.awt.Color(51, 51, 51));
        texto6.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        texto6.setText("BNB");

        texto1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto1.setForeground(new java.awt.Color(0, 102, 153));
        texto1.setText("Ingrese el nro de la Cuenta");

        texto4.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto4.setForeground(new java.awt.Color(0, 51, 102));
        texto4.setText("Ingrese  el  Nro de cuenta:");
        texto4.setToolTipText("");

        numCuenta.setBackground(new java.awt.Color(255, 204, 51));
        numCuenta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        numCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCuentaActionPerformed(evt);
            }
        });

        confirmar.setBorderPainted(false);
        confirmar.setContentAreaFilled(false);
        confirmar.setFocusPainted(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        texto5.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto5.setForeground(new java.awt.Color(0, 51, 102));
        texto5.setText("(Depositar)");
        texto5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(texto4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(628, 628, 628))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(texto1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(texto5)
                                .addGap(238, 238, 238))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))))
                .addComponent(imagen2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(texto6)
                        .addGap(26, 26, 26)
                        .addComponent(texto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texto5)
                        .addGap(53, 53, 53)
                        .addComponent(texto4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(imagen2)))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Maneja el evento de acción cuando se realiza una acción en el campo de texto de número de cuenta.
     * 
     * @param evt el evento de acción
     */
    private void numCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaActionPerformed
    /**
     * Maneja el evento de acción cuando se hace clic en el botón confirmar.
     * 
     * @param evt el evento de acción
     */
    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
          accionAlApretar();
    }//GEN-LAST:event_confirmarActionPerformed

    
    /**
     * Realiza la acción de verificar la cuenta destino e inicia la transacción si todas las condiciones se cumplen.
     */
    public void accionAlApretar(){
    CambiosEnSaldo cambios = new CambiosEnSaldo();
        cuentaADepositar = numCuenta.getText();
    boolean verificarExistencia =  cambios.verificarCuenta("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuentaADepositar+".txt");
   boolean verificarLaMisma = cambios.verificarMisma("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuentaADepositar+".txt");
    boolean verficarMoneda = cambios.verificarMonedaCoin("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuentaADepositar+".txt","C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt");  
    if(cuenta.equals(cuentaADepositar)){
        JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR LA CUENTA ES LA MISMA");
        menu v = new menu(tarjeta,cuenta);
           v.setVisible(true);
             dispose();
    }
    else{
    if(verificarExistencia){
          if(verficarMoneda){
              transaccionIII t = new transaccionIII(cuenta,tarjeta,cuentaADepositar);
               t.setVisible(true);
                    dispose();
          }else{
                JOptionPane.showMessageDialog(null, "LAS MONEDA QUE USTED MANEJA NO COINCIDE CON LA CUENTA A LA QUE INTENTA DEPOSITAR"+"\n"+"FAVOR DE CAMBIAR DE MONEDA");
                menu v = new menu(tarjeta,cuenta);
           v.setVisible(true);
             dispose();
          }
      }
    else{
          JOptionPane.showMessageDialog(null, "LA CUENTA A LA QUE INTENTA DEPOSITAR NO EXISTE!");
      menu v = new menu(tarjeta,cuenta);
           v.setVisible(true);
             dispose();
    }                                         
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new OtraCuenta(cuenta,tarjeta).setVisible(true);
            }
        });
    }
    /**
     * Clase interna para representar un panel con una imagen de fondo.
     */
    class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * Establece un ícono redimensionado en un botón.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @return el ícono redimensionado
     */
     public Icon setIcono(String url,JButton b){
         ImageIcon  icon= new ImageIcon(getClass().getResource(url)); 
         int ancho =b.getWidth();
         int alto =b.getHeight();
         ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT)); 
         return icono;
     }
     /**
     * Establece un ícono redimensionado en un botón cuando se presiona.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @param ancho el ancho del ícono redimensionado
     * @param alto el alto del ícono redimensionado
     * @return el ícono redimensionado
     */
     public Icon setIconoPrecionado(String url,JButton b,int ancho,int alto){
       
         ImageIcon icon= new ImageIcon(getClass().getResource(url));
          int  width = b.getWidth()- ancho;
          int height = b.getHeight() - alto;
          ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width,height,Image.SCALE_DEFAULT));
          return icono;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel imagen2;
    private javax.swing.JTextField numCuenta;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    // End of variables declaration//GEN-END:variables
  }
