/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Clase encargada de realizar los retiros solicitados
 * @author Milena
 */
public class retiros extends javax.swing.JFrame {
     static String cuenta;
     static String tarjeta;
    public Fondo imagen = new Fondo();  
    /**
     * Crea una instancia de la clase
     * @param cuenta
     * @param tarjeta 
     */
    public retiros(String cuenta, String tarjeta) {
        this.cuenta=cuenta;
        this.tarjeta=tarjeta;
     this.setContentPane(imagen);
        initComponents();
        setResizable(false);
                /*---------------------------------------------- parte de los botones1----------------------------------------------*/
        BTONDiez.setIcon(setIcono("/imagenes/10bs.png",BTONDiez));
        BTONDiez.setPressedIcon(setIconoPrecionado("/imagenes/10bs.png",BTONDiez,30,30));
              /*---------------------------------------------- parte de los botones2----------------------------------------------*/
        BTNCINCUENTA.setIcon(setIcono("/imagenes/50bs.png",BTNCINCUENTA));
        BTNCINCUENTA.setPressedIcon(setIconoPrecionado("/imagenes/50bs.png",BTNCINCUENTA,30,30));
           /*---------------------------------------------- parte de los botones3----------------------------------------------*/
        BTNSETENTA.setIcon(setIcono("/imagenes/70bs.png",BTNSETENTA));
        BTNSETENTA.setPressedIcon(setIconoPrecionado("/imagenes/70bs.png",BTNSETENTA,30,30));
           /*---------------------------------------------- parte de los botones4----------------------------------------------*/
        BTNCIEN.setIcon(setIcono("/imagenes/100bs.png",BTNCIEN));
        BTNCIEN.setPressedIcon(setIconoPrecionado("/imagenes/100bs.png",BTNCIEN,30,30));
           /*---------------------------------------------- parte de los botones5----------------------------------------------*/
        BTNCIENTOCINCUENTA.setIcon(setIcono("/imagenes/150bs.png",BTNCIENTOCINCUENTA));
        BTNCIENTOCINCUENTA.setPressedIcon(setIconoPrecionado("/imagenes/150bs.png",BTNCIENTOCINCUENTA,30,30));
           /*---------------------------------------------- parte de los botones6----------------------------------------------*/
        BTNDOSIENTOS.setIcon(setIcono("/imagenes/200bs.png",BTNDOSIENTOS));
        BTNDOSIENTOS.setPressedIcon(setIconoPrecionado("/imagenes/200bs.png",BTNDOSIENTOS,30,30));
         /*---------------------------------------------- parte de los botones7----------------------------------------------*/
        saldo7.setIcon(setIcono("/imagenes/otroMonto.png",saldo7));
        saldo7.setPressedIcon(setIconoPrecionado("/imagenes/otroMonto.png",saldo7,30,30));
         /*---------------------------------------------- parte de los botones8----------------------------------------------*/
         
        atras.setIcon(setIcono("/imagenes/atras.png",atras));
        atras.setPressedIcon(setIconoPrecionado("/imagenes/atras.png",atras,30,30));
        
    }
    
    CambiosEnSaldo cambio = new CambiosEnSaldo();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        BTNCINCUENTA = new javax.swing.JButton();
        BTNSETENTA = new javax.swing.JButton();
        BTNCIEN = new javax.swing.JButton();
        BTNCIENTOCINCUENTA = new javax.swing.JButton();
        BTNDOSIENTOS = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        BTONDiez = new javax.swing.JButton();
        saldo7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto2.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 51, 102));
        texto2.setText("Elige el tipo  el monto  que quiera Retirar");

        texto1.setBackground(new java.awt.Color(51, 51, 51));
        texto1.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        texto1.setText("BNB");

        BTNCINCUENTA.setBorderPainted(false);
        BTNCINCUENTA.setContentAreaFilled(false);
        BTNCINCUENTA.setFocusPainted(false);
        BTNCINCUENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCINCUENTAActionPerformed(evt);
            }
        });

        BTNSETENTA.setBorderPainted(false);
        BTNSETENTA.setContentAreaFilled(false);
        BTNSETENTA.setFocusPainted(false);
        BTNSETENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSETENTAActionPerformed(evt);
            }
        });

        BTNCIEN.setBorderPainted(false);
        BTNCIEN.setContentAreaFilled(false);
        BTNCIEN.setFocusPainted(false);
        BTNCIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCIENActionPerformed(evt);
            }
        });

        BTNCIENTOCINCUENTA.setBorderPainted(false);
        BTNCIENTOCINCUENTA.setContentAreaFilled(false);
        BTNCIENTOCINCUENTA.setFocusPainted(false);
        BTNCIENTOCINCUENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCIENTOCINCUENTAActionPerformed(evt);
            }
        });

        BTNDOSIENTOS.setBorderPainted(false);
        BTNDOSIENTOS.setContentAreaFilled(false);
        BTNDOSIENTOS.setFocusPainted(false);
        BTNDOSIENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDOSIENTOSActionPerformed(evt);
            }
        });

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setFocusPainted(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        BTONDiez.setBorderPainted(false);
        BTONDiez.setContentAreaFilled(false);
        BTONDiez.setFocusPainted(false);
        BTONDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTONDiezActionPerformed(evt);
            }
        });

        saldo7.setBorderPainted(false);
        saldo7.setContentAreaFilled(false);
        saldo7.setFocusPainted(false);
        saldo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldo7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(texto2, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNCINCUENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTONDiez, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSETENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCIEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCIENTOCINCUENTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDOSIENTOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(saldo7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(texto1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(texto2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTONDiez, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCINCUENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCIENTOCINCUENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNDOSIENTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSETENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(saldo7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Vuelve a la ventana del menú
     * @param evt Click en el botón 
     */
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
               menu  v = new menu(tarjeta,cuenta);
      
        v.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_atrasActionPerformed
    /**
     * Va a la ventana para ingresar otro monto
     * @param evt Click en el botón
     */
    private void saldo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldo7ActionPerformed
             OtroMonto v = new OtroMonto(cuenta,tarjeta);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_saldo7ActionPerformed
    /**
     * Realiza el retiro de 10
     * @param evt Click en el botón
     */
    private void BTONDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTONDiezActionPerformed
    //----------------------------------------------------------------------------------------------------------------------
        cambio.DecrementoSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",10.0,cuenta);
        //----------------------------------------------------------------------------------------------------------------------
     menu i = new menu(tarjeta,cuenta);
     i.setVisible(true);
      dispose(); 
    }//GEN-LAST:event_BTONDiezActionPerformed
    /**
     * Realiza el retiro de 50
     * @param evt Click en el botón
     */
    private void BTNCINCUENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCINCUENTAActionPerformed
        //----------------------------------------------------------------------------------------------------------------------
        cambio.DecrementoSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",50.0,cuenta);
        //----------------------------------------------------------------------------------------------------------------------
     menu i = new menu(tarjeta,cuenta);
     i.setVisible(true);
      dispose(); 
    }//GEN-LAST:event_BTNCINCUENTAActionPerformed
    /**
     * Realiza el retiro de 200
     * @param evt Click en el botón
     */
    private void BTNDOSIENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDOSIENTOSActionPerformed
     //----------------------------------------------------------------------------------------------------------------------
        cambio.DecrementoSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",200.0,cuenta);
        //----------------------------------------------------------------------------------------------------------------------
     menu i = new menu(tarjeta,cuenta);
     i.setVisible(true);
      dispose(); 
    }//GEN-LAST:event_BTNDOSIENTOSActionPerformed
    /**
     * Realiza el retiro de 70
     * @param evt Click en el botón
     */
    private void BTNSETENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSETENTAActionPerformed
      //----------------------------------------------------------------------------------------------------------------------
        cambio.DecrementoSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",70.0,cuenta);
        //----------------------------------------------------------------------------------------------------------------------
     menu i = new menu(tarjeta,cuenta);
     i.setVisible(true);
      dispose(); 
    }//GEN-LAST:event_BTNSETENTAActionPerformed
    /**
     * Realiza el retiro de 100
     * @param evt Click en el botón
     */
    private void BTNCIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCIENActionPerformed
      //----------------------------------------------------------------------------------------------------------------------
        cambio.DecrementoSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",100.0,cuenta);
        //----------------------------------------------------------------------------------------------------------------------
     menu i = new menu(tarjeta,cuenta);
     i.setVisible(true);
      dispose(); 
    }//GEN-LAST:event_BTNCIENActionPerformed
    /**
     * Realiza el retiro de 150
     * @param evt Click en el botón
     */
    private void BTNCIENTOCINCUENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCIENTOCINCUENTAActionPerformed
        //----------------------------------------------------------------------------------------------------------------------
        cambio.DecrementoSaldo("C:\\Users\\Milena\\taller de pogra\\cuentas\\"+cuenta+".txt",150.0,cuenta);
        //---------------------------------------------------------------------------------------------------------------------
     menu i = new menu(tarjeta,cuenta);
     i.setVisible(true);
      dispose(); 
    }//GEN-LAST:event_BTNCIENTOCINCUENTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
     new retiros(cuenta,tarjeta).setVisible(true);
            }
        });
    }
    /**
     * Clase interna para representar un panel con una imagen de fondo.
     */
  class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * Establece un ícono redimensionado en un botón.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @return el ícono redimensionado
     */
     public Icon setIcono(String url,JButton b){
         ImageIcon  icon= new ImageIcon(getClass().getResource(url)); 
         int ancho =b.getWidth();
         int alto =b.getHeight();
         ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT)); 
         return icono;
     }
    /**
     * Establece un ícono redimensionado en un botón cuando se presiona.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @param ancho el ancho del ícono redimensionado
     * @param alto el alto del ícono redimensionado
     * @return el ícono redimensionado
     */
     public Icon setIconoPrecionado(String url,JButton b,int ancho,int alto){
       
         ImageIcon icon= new ImageIcon(getClass().getResource(url));
          int  width = b.getWidth()- ancho;
          int height = b.getHeight() - alto;
          ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width,height,Image.SCALE_DEFAULT));
          return icono;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCIEN;
    private javax.swing.JButton BTNCIENTOCINCUENTA;
    private javax.swing.JButton BTNCINCUENTA;
    private javax.swing.JButton BTNDOSIENTOS;
    private javax.swing.JButton BTNSETENTA;
    private javax.swing.JButton BTONDiez;
    private javax.swing.JButton atras;
    private javax.swing.JButton saldo7;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
