/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 * Esta clase representa una interfaz gráfica de usuario para realizar transacciones entre cuentas.
 * 
 * @author Milena
 */
public class transacciones extends javax.swing.JFrame {
     static String cuenta;
     static String tarjeta;
    public Fondo imagen = new Fondo();  
    public transacciones(String cuenta,String tarjeta) {
        this.cuenta=cuenta;
        this.tarjeta=tarjeta;
     this.setContentPane(imagen);
        initComponents();
        setResizable(false);
                /*---------------------------------------------- parte de los botones1----------------------------------------------*/
        saldo.setIcon(setIcono("/imagenes/10bs.png",saldo));
        saldo.setPressedIcon(setIconoPrecionado("/imagenes/10bs.png",saldo,30,30));
              /*---------------------------------------------- parte de los botones2----------------------------------------------*/
        saldo1.setIcon(setIcono("/imagenes/50bs.png",saldo1));
        saldo1.setPressedIcon(setIconoPrecionado("/imagenes/50bs.png",saldo1,30,30));
           /*---------------------------------------------- parte de los botones3----------------------------------------------*/
        saldo2.setIcon(setIcono("/imagenes/70bs.png",saldo2));
        saldo2.setPressedIcon(setIconoPrecionado("/imagenes/70bs.png",saldo2,30,30));
           /*---------------------------------------------- parte de los botones4----------------------------------------------*/
        saldo3.setIcon(setIcono("/imagenes/100bs.png",saldo3));
        saldo3.setPressedIcon(setIconoPrecionado("/imagenes/100bs.png",saldo3,30,30));
           /*---------------------------------------------- parte de los botones5----------------------------------------------*/
        saldo4.setIcon(setIcono("/imagenes/150bs.png",saldo4));
        saldo4.setPressedIcon(setIconoPrecionado("/imagenes/150bs.png",saldo4,30,30));
           /*---------------------------------------------- parte de los botones6----------------------------------------------*/
        saldo5.setIcon(setIcono("/imagenes/200bs.png",saldo5));
        saldo5.setPressedIcon(setIconoPrecionado("/imagenes/200bs.png",saldo5,30,30));
         /*---------------------------------------------- parte de los botones7----------------------------------------------*/
        saldo7.setIcon(setIcono("/imagenes/otroMonto.png",saldo7));
        saldo7.setPressedIcon(setIconoPrecionado("/imagenes/otroMonto.png",saldo7,30,30));
         /*---------------------------------------------- parte de los botones8----------------------------------------------*/
         
        atras.setIcon(setIcono("/imagenes/atras.png",atras));
        atras.setPressedIcon(setIconoPrecionado("/imagenes/atras.png",atras,30,30));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        saldo1 = new javax.swing.JButton();
        saldo2 = new javax.swing.JButton();
        saldo3 = new javax.swing.JButton();
        saldo4 = new javax.swing.JButton();
        saldo5 = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        saldo7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto2.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 51, 102));
        texto2.setText("Elige el tipo  el monto  que quiera Transferir");

        texto1.setBackground(new java.awt.Color(51, 51, 51));
        texto1.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        texto1.setText("BNB");

        saldo1.setBorderPainted(false);
        saldo1.setContentAreaFilled(false);
        saldo1.setFocusPainted(false);

        saldo2.setBorderPainted(false);
        saldo2.setContentAreaFilled(false);
        saldo2.setFocusPainted(false);
        saldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldo2ActionPerformed(evt);
            }
        });

        saldo3.setBorderPainted(false);
        saldo3.setContentAreaFilled(false);
        saldo3.setFocusPainted(false);

        saldo4.setBorderPainted(false);
        saldo4.setContentAreaFilled(false);
        saldo4.setFocusPainted(false);

        saldo5.setBorderPainted(false);
        saldo5.setContentAreaFilled(false);
        saldo5.setFocusPainted(false);

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setFocusPainted(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        saldo.setBorderPainted(false);
        saldo.setContentAreaFilled(false);
        saldo.setFocusPainted(false);

        saldo7.setBorderPainted(false);
        saldo7.setContentAreaFilled(false);
        saldo7.setFocusPainted(false);
        saldo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldo7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(saldo7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(texto2)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(saldo7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
               inicio  v = new inicio();
      
        v.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void saldo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldo7ActionPerformed
             OtroMonto v = new OtroMonto(cuenta,tarjeta);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_saldo7ActionPerformed

    private void saldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new transacciones(cuenta,tarjeta).setVisible(true);
            }
        });
    }
    /**
     * Clase interna para representar un panel con una imagen de fondo.
     */
  class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    /**
     * Establece un ícono redimensionado en un botón.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @return el ícono redimensionado
     */
     public Icon setIcono(String url,JButton b){
         ImageIcon  icon= new ImageIcon(getClass().getResource(url)); 
         int ancho =b.getWidth();
         int alto =b.getHeight();
         ImageIcon icono= new ImageIcon(icon.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT)); 
         return icono;
     }
    /**
     * Establece un ícono redimensionado en un botón cuando se presiona.
     * 
     * @param url la ruta del ícono
     * @param b el botón en el que se establecerá el ícono
     * @param ancho el ancho del ícono redimensionado
     * @param alto el alto del ícono redimensionado
     * @return el ícono redimensionado
     */
     public Icon setIconoPrecionado(String url,JButton b,int ancho,int alto){
       
         ImageIcon icon= new ImageIcon(getClass().getResource(url));
          int  width = b.getWidth()- ancho;
          int height = b.getHeight() - alto;
          ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width,height,Image.SCALE_DEFAULT));
          return icono;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton saldo;
    private javax.swing.JButton saldo1;
    private javax.swing.JButton saldo2;
    private javax.swing.JButton saldo3;
    private javax.swing.JButton saldo4;
    private javax.swing.JButton saldo5;
    private javax.swing.JButton saldo7;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
